import Image from 'next/image';
import Header from '../../Components/Header';
import Footer from '../../Components/Footer';
import MoreGames from '../../Components/MoreGames';
import QuestionFAQ from '../../Components/QuestionFAQ';
import AdSense from '../../Components/AdSense';
import AdsterraNativeBanner from '../../Components/AdsterraNativeBanner';
import AdsterraBanner300x250 from '../../Components/AdsterraBanner300x250';
import GameWithSidebarAds from '../../Components/GameWithSidebarAds';
import EmbedDetect from '../../Components/EmbedDetect';
import GuessPromptGame from './GuessPromptGame';
import en from '@/locales/en.json';
import { getTranslation } from '@/lib/i18n';
import gp from '../gamePage.module.css';

export default async function GuessPromptPage({ params }) {
  const locale = params?.lang || 'en';
  const t = locale === 'en' ? en : (await getTranslation(locale)) || en;

  return (
    <>
      <AdSense />
      <EmbedDetect />
      <Header />
      <main className={gp.pageWrapper}>
        <section className={gp.gameSection}>
          <GameWithSidebarAds>
            <GuessPromptGame />
          </GameWithSidebarAds>
        </section>

        <MoreGames current="guess-prompt" />

        <AdsterraNativeBanner />

        <section className={gp.hero}>
          <div className={gp.heroInner}>
            <Image src="/logo-guess-prompt.png" alt="Guess the Prompt" width={80} height={80} className={gp.heroLogo} />
            <h1 className={gp.heroTitle}>Guess the Prompt</h1>
            <p className={gp.heroSubtitle}>See an image and guess which prompt created it from 4 choices!</p>
          </div>
        </section>

        <div style={{ display: 'flex', justifyContent: 'center', padding: '1rem 0' }}>
          <AdsterraBanner300x250 />
        </div>

        <section className={gp.aboutSection}>
          <div className={gp.container}>
            <h2 className={gp.sectionTitle}>What Is Guess the Prompt?</h2>
            <div className={gp.aboutContent}>
              <p>Guess the Prompt is a visual guessing game where you see an image — either drawn by a human or generated by AI — and try to figure out which prompt created it.</p>
              <p>Each round gives you 4 possible prompts to choose from. Pick the right one to keep your streak alive. One wrong answer and it's game over!</p>
              <p>All images come from real players of Your AI Slop Bores Me, making every round unique and unpredictable.</p>
            </div>
          </div>
        </section>

        <section className={gp.howtoSection}>
          <div className={gp.container}>
            <h2 className={gp.sectionTitle}>How to Play</h2>
            <div className={gp.stepsGrid}>
              <div className={gp.stepCard}>
                <div className={gp.stepNumber}>1</div>
                <h3>Look at the Image</h3>
                <p>Each round shows you a drawing or AI-generated image from the community.</p>
              </div>
              <div className={gp.stepCard}>
                <div className={gp.stepNumber}>2</div>
                <h3>Pick the Prompt</h3>
                <p>Read the 4 options and choose which prompt you think created the image.</p>
              </div>
              <div className={gp.stepCard}>
                <div className={gp.stepNumber}>3</div>
                <h3>Keep Your Streak</h3>
                <p>Get it right and move on. Get it wrong and the game ends. How far can you go?</p>
              </div>
            </div>
          </div>
        </section>

        <section className={gp.howtoSection}>
          <div className={gp.container}>
            <h2 className={gp.sectionTitle}>Tips for Guessing</h2>
            <div className={gp.featuresGrid}>
              <div className={gp.featureCard}>
                <span className={gp.featureIcon}>🔍</span>
                <h3>Look for Details</h3>
                <p>Specific objects or animals in the image often match keywords in the correct prompt.</p>
              </div>
              <div className={gp.featureCard}>
                <span className={gp.featureIcon}>🎨</span>
                <h3>Consider the Style</h3>
                <p>Human drawings tend to be simpler and rougher. AI images are usually more polished.</p>
              </div>
              <div className={gp.featureCard}>
                <span className={gp.featureIcon}>🎯</span>
                <h3>Eliminate Options</h3>
                <p>If you're unsure, rule out prompts that clearly don't match what you see.</p>
              </div>
            </div>
          </div>
        </section>

        <div style={{ display: 'flex', justifyContent: 'center', padding: '1rem 0' }}>
          <AdsterraBanner300x250 />
        </div>

        <section className={gp.faqSection}>
          <div className={gp.container}>
            <h2 className={gp.sectionTitle}>Frequently Asked Questions</h2>
            <div className={gp.faqList}>
              <QuestionFAQ question="Where do the images come from?" answer="All images are created by real players in 'Your AI Slop Bores Me' — some are hand-drawn by humans, others are AI-generated." />
              <QuestionFAQ question="How many rounds can I play?" answer="There's no limit! Keep guessing correctly and your streak keeps going. One wrong answer ends the game." />
              <QuestionFAQ question="Is this free to play?" answer="Yes, completely free. No sign-up required." />
              <QuestionFAQ question="Can I submit my own drawings?" answer="Yes! Play the main game 'Your AI Slop Bores Me' and your drawings may appear in Guess the Prompt rounds." />
            </div>
          </div>
        </section>
      </main>
      <Footer t={t} />
    </>
  );
}
