import { NextResponse } from 'next/server';
import { findSimilarImage } from '@/lib/imageCache';

export const dynamic = 'force-dynamic';

// GET: AI fallback — only search community image pool for similar images
// Text responses should be generated by /api/chat for relevance
// ?type=text|image&prompt=xxx
export async function GET(req) {
  const { searchParams } = new URL(req.url);
  const askType = searchParams.get('type') || 'text';
  const prompt = searchParams.get('prompt') || '';

  try {
    // Only search image cache for image requests
    let cachedImageUrl = null;
    if (askType === 'image' && prompt) {
      cachedImageUrl = await findSimilarImage(prompt);
    }

    return NextResponse.json({
      text: null,
      image_url: cachedImageUrl,
    });
  } catch (error) {
    console.error('Fallback fetch error:', error);
    return NextResponse.json({ text: null, image_url: null });
  }
}
