import Link from 'next/link';
import Header from '../Components/Header';
import Footer from '../Components/Footer';
import styles from '../legal.module.css';

export const metadata = {
  title: 'Terms of Use – Your AI Slop Bores Me',
  description: 'Terms of Use for Your AI Slop Bores Me game website.',
};

export default function TermsOfUse() {
  return (
    <>
      <Header />
      <div className={styles.legalPage}>
        <h1>Terms of Use</h1>
        <p className={styles.lastUpdated}>Last updated: March 10, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using Your AI Slop Bores Me Game ("the Site") at youraislopboresmegame.com,
          you agree to be bound by these Terms of Use. If you do not agree, please do not use the Site.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          The Site provides a free browser-based game called "Your AI Slop Bores Me" where players
          interact with AI-generated prompts, submit text and drawing responses, and earn tokens.
          This is a fan-made project inspired by the original game at youraislopbores.me created by mikidoodle.
        </p>

        <h2>3. User Conduct</h2>
        <p>When using the Site, you agree not to:</p>
        <ul>
          <li>Submit content that is illegal, harmful, threatening, abusive, hateful, or otherwise objectionable.</li>
          <li>Attempt to bypass rate limits, abuse API endpoints, or interfere with the Site's operation.</li>
          <li>Use automated tools, bots, or scripts to access the Site or its APIs beyond normal gameplay.</li>
          <li>Reverse-engineer, scrape, or redistribute the Site's content or services.</li>
          <li>Impersonate any person or entity, or misrepresent your affiliation.</li>
        </ul>

        <h2>4. User-Generated Content</h2>
        <p>
          You retain ownership of text and drawings you create during gameplay. By submitting content,
          you grant us a non-exclusive, royalty-free license to process it through our AI services
          for the purpose of gameplay. We do not permanently store or redistribute your content.
        </p>

        <h2>5. AI-Generated Content</h2>
        <p>
          Responses and images generated by AI during gameplay are provided "as is" for entertainment.
          AI-generated content may be inaccurate, nonsensical, or inappropriate. We are not responsible
          for the content produced by AI models and do not endorse any statements made by AI responses.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          The original "Your AI Slop Bores Me" game concept is created by mikidoodle. This Site is
          a fan-made project. All original code, design, and content on this Site are the property of
          the Site operators. The Site's source code is available on{' '}
          <a href="https://github.com/codaaiteam/yourslopai" target="_blank" rel="noopener noreferrer">GitHub</a>.
        </p>

        <h2>7. Disclaimers</h2>
        <ul>
          <li>The Site is provided "as is" without warranties of any kind.</li>
          <li>We do not guarantee uninterrupted or error-free service.</li>
          <li>Game progress stored in localStorage may be lost if you clear your browser data.</li>
          <li>API availability depends on third-party services (DeepSeek, KIE AI) and may change without notice.</li>
        </ul>

        <h2>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, the Site operators shall not be liable for any
          indirect, incidental, special, or consequential damages arising from your use of the Site,
          including but not limited to loss of data, loss of tokens, or inability to access the service.
        </p>

        <h2>9. Rate Limits & Fair Use</h2>
        <p>
          To ensure fair access for all users, the Site enforces rate limits on API usage.
          Exceeding these limits may result in temporary restrictions. Systematic abuse may result
          in permanent blocking.
        </p>

        <h2>10. Modifications</h2>
        <p>
          We reserve the right to modify these Terms at any time. Continued use of the Site after
          changes constitutes acceptance of the updated Terms.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by applicable law. Any disputes shall be resolved in the
          appropriate jurisdiction.
        </p>

        <h2>12. Contact</h2>
        <p>
          For questions about these Terms, please reach out via our
          {' '}<a href="https://github.com/codaaiteam/yourslopai" target="_blank" rel="noopener noreferrer">GitHub repository</a>.
        </p>

        <Link href="/" className={styles.backLink}>&larr; Back to Home</Link>
      </div>
      <Footer />
    </>
  );
}
